'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17929
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Crypter.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;Assembly: AssemblyTitle(&quot;%Title%&quot;)&gt; 
        '''&lt;Assembly: AssemblyDescription(&quot;%Description%&quot;)&gt; 
        '''&lt;Assembly: AssemblyCompany(&quot;%Company%&quot;)&gt; 
        '''&lt;Assembly: AssemblyProduct(&quot;%Product%&quot;)&gt; 
        '''&lt;Assembly: AssemblyCopyright(&quot;%Copyright%&quot;)&gt; 
        '''&lt;Assembly: AssemblyTrademark(&quot;%Trademark%&quot;)&gt; 
        '''&lt;Assembly: AssemblyFileVersion(&quot;%FileVersion%&quot;)&gt; .
        '''</summary>
        Friend ReadOnly Property Asem() As String
            Get
                Return ResourceManager.GetString("Asem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Capture() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Capture", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property DarkFire() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("DarkFire", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Mono_Cecil() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Mono_Cecil", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property pourquoi() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("pourquoi", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Imports System, Microsoft.VisualBasic
        '''Imports System.Reflection
        '''Imports System.Text
        '''Imports System.Security.Cryptography
        '''Imports System.IO.Compression
        '''Imports System.IO
        '''Imports System.Diagnostics
        '''
        '''&apos;[ASEMBLYCODE]
        '''&lt;Assembly: AssemblyKeyFileAttribute(&quot;STRONGNAMELOCATION&quot;)&gt; 
        '''
        '''Public Class _BASE
        '''    Shared ASM As Assembly = Assembly.GetExecutingAssembly()
        '''    Shared RM As New Resources.ResourceManager(&quot;Z&quot;, ASM)
        '''    Shared Bind As Boolean = %BindCheck%
        '''    Shared Once As Boolean = %OnceCheck%
        '''     [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Source() As String
            Get
                Return ResourceManager.GetString("Source", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Xenocode() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Xenocode", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
    End Module
End Namespace
